import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import TabContentDesign from "@/components/page/tab-content-design";

import { BreadCrumb } from "@/components/breadcrumbs";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { twMerge } from "tailwind-merge";

const notoSansJp = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          "antialiased font-noto-sans-jp h-[100dvh] max-h-[100dvh]",
          notoSansJp.variable,
        )}
      >
        <div className="grid h-[100dvh] max-h-[100dvh] grid-cols-[1fr_4fr_4fr] grid-rows-[2.5rem_1fr] gap-2 p-2">
          <div className="rounded-md bg-slate-400" />
          <div className="flex items-center rounded-md bg-slate-200 px-2">
            <BreadCrumb />
          </div>
          <div className="row-span-2 rounded-md">
            <Tabs
              defaultValue="history"
              className="w-full"
            >
              <TabsList>
                <TabsTrigger value="history">改変履歴</TabsTrigger>
                <TabsTrigger value="auxiliary">AI補助</TabsTrigger>
              </TabsList>
              <TabsContent value="history">
                <TabContentDesign />
              </TabsContent>
              <TabsContent value="auxiliary">
                Change your password here.
              </TabsContent>
            </Tabs>
          </div>
          <div className="rounded-md bg-slate-500" />
          <div className="h-full overflow-y-scroll rounded-md bg-gray-100">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
